### ISSUE TITLE
[feat] 기본 레이아웃 설계 & 노출 판매기간 설정 

### ISSUE THREAD

**Issue by cloud0406** [react-playground-assignment-practice/product_management_page#1]
### 설명
* 메뉴바 UI 제작

   * '상품' 메뉴 클릭시 드롭다운 이벤트

* 노출 및 판매 기간 설정 UI 제작

* '제한 없음', '미노출' 클릭시 기간 설정 동작 제한

* '노출 기간 설정' 클릭시 상세 날짜 설정 (MUI 에서 달력 및 시간 지정 컴포넌트 사용)

## ToDo
- [ ] navbar UI(sidebar) + drop down event + 기본 UI
- [ ] 노출 & 판매 기간 UI
- [ ] 노출 기간 설정 with MUI 활용
- [ ] Radio Button 이벤트 처리

**Comment by cheewr85** [comment]
- 추가로 gitignore 설정을 통해서 PR시 불필요한 프로젝트 파일 올리는 것 방지 필요
